# frozen_string_literal: true

source 'https://rubygems.org'

ruby file: '.ruby-version'

# Core exercises: Ruby, tests, tasks, and linting.
gem 'activesupport', '~> 8.1'
gem 'minitest', '~> 5.25'
gem 'rake', '~> 13.0'
gem 'rubocop', '~> 1.86', require: false

# Rack modules and rack-api project.
gem 'puma', '~> 7.0'
gem 'rack', '~> 3.2'
gem 'rack-test', '~> 2.2'
gem 'rackup', '~> 2.2'

# Rails, authentication, and API modules.
gem 'devise', '~> 4.9'
gem 'grape', '~> 2.4'
gem 'grape-entity', '~> 1.0'
gem 'grape-swagger', '~> 2.1'
gem 'rails', '~> 8.1'
gem 'sqlite3', '~> 2.7'
